services:
  - type: web
    name: blog
    env: node

    plan: starter
    region: ohio
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    healthCheckPath: /_health
    disk:
      name: blog-uploads
      mountPath: /opt/render/project/src/public/uploads
      sizeGB: 1
    envVars:
      - key: NODE_VERSION
        value: 20.1
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: blog
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true

databases:
  - name: blog
    plan: starter
